name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Redis streams service
        uses: actions/redis@v1.8.0
        with:
          url: redis://localhost:6379
          
      - name: Build proyect
        run: cargo build --verbose
        
      - name: Run proyect tests
        run: cargo test --verbose
