name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          components: llvm-tools-preview

      - name: "Setup: Install cargo-llvm-cov"
        uses: taiki-e/install-action@v2.33.22
        with:
          tool: cargo-llvm-cov

      - name: Build
        run: cargo build --workspace --all-features

      - name: Format
        run: cargo fmt --all --check

      - name: Lints
        run: cargo clippy --workspace --all-features

      - name: Unit Tests
        env:
          MIN_LINE_COVERAGE_TARGET: 80
        run: cargo llvm-cov --workspace --all-features --show-missing-lines --summary-only --fail-under-lines ${{ env.MIN_LINE_COVERAGE_TARGET }}

      - name: Doc Tests
        run: cargo test --workspace --all-features --doc
